### ISSUE TITLE
No Licence file

### ISSUE THREAD

**Issue by ndamack** [evoluteur/motivational-numerology#1]
Hi,
I have downloaded this programme and tested it on my website.  It works perfectly, however, since the folder does not include a licence file I am concerned about my legality of using this product in the future.
Could you please confirm what, if any, licence restrictions exist for this product.
Many thanks
Neill

**Comment by evoluteur** [comment]
Hi Neil,

Thanks for checking.
I'll ask the author of the book (she is a friend of mine) and get back to
you.
What web site are you planning to use the code on?
Would it be OK to give credit to Sally Faubion and link to her web site?

Regards,
Olivier

**Comment by ndamack** [comment]
Hi Oliver,

Many thanks for getting back to me so quickly.

My intention is to create a Numerology/Astrology niche site.  The project
is still in the embryonic stage at the moment and no domain name has been
registered yet.

I have created "hobby" type websites in the past and my first one was way
back in 1999 - a personalised "Letter from Santa" site.  I still try to
keep on top of it and twenty years later you can see my 2019 Christmas
offering here <https://santaletter.bookmark.com/>.  Although I may class
these and other sites I have previously created as a hobby I do
never-the-less take them all seriously.

Creating and maintaining my sites has always been done by me on a part-time
basis whilst being employed full time as a UK police officer.  But I am now
retired and whilst the Santa Letter will continue to be my #1 child I now
want to branch out.  I have always had an interest in numerology and
associated subjects and it is here that I want to go next.

I am not a coder and so the proposed numerology site will be built on a
WordPress base.  It will be substantive and include regularly updated
written and video content.

I have not decided on how the site will be monetised.  However, I
previously sold the Santa Letters as a tangible product from 1999 to 2010
and more recently as a download.  I also carry out affiliate marketing and
the Santa sacks pictured in the 2019 landing page above all have Amazon
affiliate links.  So, not only could I give credit to Sally Faubion I would
probably do it with an Amazon link tied to an image of her book.

I have no plans to sell your code or to sell access to the product it
creates however, I may use it as a list building lead magnet i.e. allow
visitors free access to the service in exchange for their email address.

I do hope the above helps you make a decision about how I may use your
product but please do get back to me if you need any further information.

All the very best
Neill

**Comment by evoluteur** [comment]
Thanks Neil. I forwarded your email to Sally. I will get back to you soon.

-Olivier

**Comment by evoluteur** [comment]
Hi Neil,

I talked to Sally Faubion. You can use the code I posted as long as you
give her credit and link to her site or books.
Let us know when you have something up and running. We will be happy to
check it out.

Thanks,
Olivier

**Comment by ndamack** [comment]
Hi Oliver,

Many thanks to you and Sally for your approval - it really is appreciated..
I will, of course, let you see the site when I have something concrete to
show you and it will include links to Sally's book.

All the very best
Neill

**Comment by ndamack** [comment]
Hi Oliver,

A quick update as promised.

I've created my website at numerologysite.com which is pretty darned basic
at the moment.  As promised, I've kept the links (not affiliate ones yet)
to Sally's book.

Still a long way to go but it's a start

All the best

Neill

**Comment by evoluteur** [comment]
Great start. Thanks for sharing. I will let Sally know.
